name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only main

    - name: Set up the database
      run: |
        cd api
        sudo su
        poetry run python manage.py collectstatic
        poetry run python manage.py makemigrations
        poetry run python manage.py migrate

    - name: Run Django tests
      run: |
        cd api
        poetry run python manage.py test
